### ISSUE TITLE
Problem installing irida linker on CentOS 7 

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [phac-nml/irida-linker#1]
I would appreciate some assistance with the irida-linker install/install.py script.  With a fresh github clone of irida-linker, and as root user, I'm trying to run the script, but am getting:

    [root@sabin irida-linker]# install/install.pl
    Perl library location? [/opt/software/ngsarchivelinker/irida-linker/install/../lib/]  
    Using /opt/software/ngsarchivelinker/irida-linker/install/../lib/ as library
    Package OAuth::Lite2::Client::UsernameAndPassword is not installed. Would you like to try to install it using cpanm? [Y,n] Y
    Running command: cpanm -L /opt/software/ngsarchivelinker/irida-linker/install/../lib/             
    OAuth::Lite2::Client::UsernameAndPassword
    ==> **Found dependencies: ExtUtils::MakeMaker**
    --> **Working on ExtUtils::MakeMaker**
    Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz ... OK
    **Configuring ExtUtils-MakeMaker-7.30 ... OK**
    ==> Found dependencies: File::Spec, Pod::Man, Encode
    --> Working on File::Spec
    Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/PathTools-3.62.tar.gz ... OK
    ==> **Found dependencies: ExtUtils::MakeMaker**
    **! Installing the dependencies failed: Module 'ExtUtils::MakeMaker' is not installed**
    **! Bailing out the installation for PathTools-3.62.**
    --> Working on Pod::Man
    Fetching http://www.cpan.org/authors/id/R/RR/RRA/podlators-4.09.tar.gz ... OK
    ==> Found dependencies: ExtUtils::MakeMaker
    ! Installing the dependencies failed: Module 'ExtUtils::MakeMaker' is not installed
    ! Bailing out the installation for podlators-4.09.
    --> Working on Encode
    ...

etc.
As well, later in install script it indicates error that: "Could not open requirements file: [Errno 2] No such file or directory: '/opt/software/ngsarchivelinker/irida-linker/install/requirements.txt' ", and indeed there doesn't appear to be that file (unless it is generated during an errorless install).

Thanks,

Damion

**Comment by tom114** [comment]
Hi Damion,

I don't have a Centos 7 machine available at the moment, but it looks like there's issues with getting MakeMaker installed.  Some quick googling came up with a few pages stating similar things
(https://www.svennd.be/cant-locate-extutilsmakemaker-pm-in-inc-centos-7/).

If you haven't already, try installing `perl-devel` and let us know how it works out.
```
yum install perl-devel
```

**Comment by Public-Health-Bioinformatics** [comment]
Thanks Tom ... tried out perl-devel but that wasn't enough.  Turns out for CentOS 7.0 users having trouble with MakeMaker, there's some kind of circular dependency in the build.  So if you run into above error, do this first, and then try install.pl

    cpanm -l /opt/software/ngsarchivelinker/irida-linker/install/../lib/ ExtUtils::MakeMaker --force

from bottom of [this thread](https://stackoverflow.com/questions/25091164/cpanm-l-broken)

Ah, for install.pl to build, also had to add a few other modules to above: Carp, Test::More and File::Spec

d.

**Comment by Public-Health-Bioinformatics** [comment]
I've made it through most of the perl install script, but ran into this:

```
Installing required python libs into /opt/software/ngsarchivelinker/irida-linker/install/../python-deps/
Running command: export PYTHONUSERBASE=/opt/software/ngsarchivelinker/irida-linker/install/../python-deps/; pip install --user -r /opt/software/ngsarchivelinker/irida-linker/install/requirements.txt
**Could not open requirements file: [Errno 2] No such file or directory: '/opt/software/ngsarchivelinker/irida-linker/install/requirements.txt'**
```

Is requirements.txt supposed to exist already?  Or was it supposed to be created by the import script?

**Comment by tom114** [comment]
Off hand I'm not sure why that's even there since I'm pretty sure the linker doesn't use any python libraries.  Try removing the whole section (8 lines) under `##Install python libs`.  I don't think it's needed and may have been committed in error.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, trying that.  Also had to adjust next instance of 

     $ret = option("Install config file to $confFile?","y");

to be

    my $ret = option("Install config file to $confFile?","y");

Which gets past above error.

However, I've run into another roadblock in trying to install module 'XML::LibXML', as below.  I think I can figure this out, but I'll say that this Centos7 and presumably Redhat install issue sounds like a liability for new installs ... any way to revise the install script to make this more reliable?

**********************

> Fetching with LWP:
> http://mirrors.gossamer-threads.com/CPAN/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0129.tar.gz
> Fetching with LWP:
> http://mirrors.gossamer-threads.com/CPAN/authors/id/S/SH/SHLOMIF/CHECKSUMS
> Checksum for /root/.cpan/sources/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0129.tar.gz ok
> Configuring S/SH/SHLOMIF/XML-LibXML-2.0129.tar.gz with Makefile.PL
> enable native perl UTF8
> running xml2-config...didn't manage to get libxml2 config, guessing
> options:
>   LIBS='-L/usr/local/lib -L/usr/lib -lxml2 -lm'
>   INC='-I/usr/local/include -I/usr/include'
> If this is wrong, Re-run as:
>   $ /usr/bin/perl Makefile.PL LIBS='-L/path/to/lib' INC='-I/path/to/include'
> 
> Checking for ability to link against xml2...no
> Checking for ability to link against libxml2...libxml2, zlib, and/or the Math library (-lm) have not been found.
> Try setting LIBS and INC values on the command line
> Or get libxml2 from
>   http://xmlsoft.org/
> If you install via RPMs, make sure you also install the -devel
> RPMs, as this is where the headers (.h files) are.
> 
> Also, you may try to run perl Makefile.PL with the DEBUG=1 parameter
> to see the exact reason why the detection of libxml2 installation
> failed or why Makefile.PL was not able to compile a test program.
> No 'Makefile' created  SHLOMIF/XML-LibXML-2.0129.tar.gz

**Comment by Public-Health-Bioinformatics** [comment]
Ah, it turns out the latest Perl 2.0129 is buggy, one is damned if one tries to install it.  [Issue thread](http://www.perlmonks.org/?node_id=1191092).  The underlying cause is this XML::LibXML depends on a linux (system?) library called "libxml2".  But I don't know enough about perl / Cpan / Cpanm to know how to say set the LIBS and INC values correctly; I can't locate libxml2 on sabin where I'm working even. I'll have to ask for perl help here...

**Comment by Public-Health-Bioinformatics** [comment]
Jun Duan had to do this additional step to get libxml2-2.7.2.tar.gz from ftp://xmlsoft.org/libxml2/

```
mkdir /opt/libxml
./configure --prefix=/opt/libxml
make
make install
And just for the install, to add /opt/libxml/bin to $PATH
Then install/install.pl worked

```

**Comment by tom114** [comment]
Closing this issue since conda is the default install for this project now.  This will work in centos7.
