### ISSUE TITLE
Installation username, password, and api key

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [phac-nml/irida-linker#2]
It is installed but I'm not yet able to run the command line linker because I don't understand which api key is being requested I think.  The installation script asks for a few configuration values:

```
-bash-4.2$ /opt/software/ngsarchivelinker/irida-linker/install/install.pl
Perl library location? [/opt/software/ngsarchivelinker/irida-linker/install/../lib/] 
Using /opt/software/ngsarchivelinker/irida-linker/install/../lib/ as library
Install config file to /home/ddooley/.irida//ngs-archive-linker.conf? [Y,n] Y
Creating directory /home/ddooley/.irida/
REST API location? [http://ngs-archive.corefacility.ca/irida-api] http://[myserver].ca:8080/irida-latest/api 
Setting base URL as http://[myserver].ca:8080/irida-latest/api in /home/ddooley/.irida//ngs-archive-linker.conf
Galaxy URL location? [http://galaxy.corefacility.ca/] http://[myserver].ca:9090/
Setting Galaxy URL as http://[myserver].ca:9090/ in /home/ddooley/.irida//ngs-archive-linker.conf
Galaxy api key? [None] [a big long key here]
Setting Galaxy URL as [same as above] in /home/ddooley/.irida//ngs-archive-linker.conf
```
I think it is my IRIDA user id and password that is being asked for when I run the tool right (such that I have rights over the project I specify to link to)?  So then is it really the Galaxy API key that is being asked for, and if so, for what galaxy account, i.e. is it an admin level galaxy acct needed?  (My IRIDA user account isn't set up in galaxy).  Or is it actually an IRIDA api key being requested, which I presume has to be set up by an IRIDA admin?  I couldn't find this in the docs.
Thanks,

**Comment by apetkau** [comment]
I believe the Galaxy API key/account being asked for are used in other scripts which don't seem to be committed to this repository (they move files between IRIDA and Galaxy).  They aren't needed for `ngsArchiveLinker.pl` though, so you can safely ignore them.

**Comment by tom114** [comment]
Installation script correctly no longer asks for these options.  They were borrowed from an old script.
